dtb-y += exynos7885-a7y18lte_eur_open_00.dtb
dtb-y += exynos7885-a7y18lte_eur_open_01.dtb
dtb-y += exynos7885-a7y18lte_eur_open_03.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
